import { z } from "zod";
import { createTRPCRouter, protectedProcedure } from "../trpc";
import { TRPCError } from "@trpc/server";
import { db } from "@/server/db";
import { CacheService } from "@/lib/services/cache-service";
import { cacheKeys, CACHE_TTL } from "@/lib/redis/client";
import {
  analyzeProjectMigration,
  detectTechStack,
  getMigrationSuggestions,
} from "@/lib/ai/migration-engine";
import { GitHubMigrationService } from "@/lib/services/migration-service";

export const migrationRouter = createTRPCRouter({
  // Analyze migration
  analyzeMigration: protectedProcedure
    .input(
      z.object({
        projectId: z.string(),
        target: z.string(),
        type: z.enum(["framework", "language", "architecture", "refactor"]),
        forceRefresh: z.boolean().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      try {
        const { projectId, target, type, forceRefresh = false } = input;
        const userId = ctx.user.userId!;

        console.log("🔍 Analyzing migration:", {
          projectId,
          target,
          type,
          userId,
        });

        // Check access
        const access = await db.userToProject.findUnique({
          where: { userId_projectId: { userId, projectId } },
        });

        if (!access) {
          throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
        }

        const cacheKey = `migration:analysis:${projectId}:${type}:${target}`;

        // Get from cache or analyze
        const analysis = await CacheService.getOrSet(
          cacheKey,
          async () => {
            console.log("🔄 Generating fresh migration analysis...");
            return await analyzeProjectMigration(projectId, target, type);
          },
          {
            ttl: CACHE_TTL.MIGRATION_ANALYSIS,
            forceRefresh,
          },
        );

        console.log("✅ Migration analysis complete:", analysis);

        //  Save migration plan with proper data
        let plan;
        try {
          plan = await db.migrationPlan.create({
            data: {
              projectId,
              name: `Migrate to ${target}`,
              description: analysis.summary || "Migration plan generated by AI",
              type: type,
              status: "ready",
              source: { current: "current" },
              target: { target: target },
              steps: analysis.steps || [],
              risks: analysis.risks || [],
              files: analysis.files || [],
              dependencies: analysis.dependencies || [],
              userId,
            },
          });
          console.log("✅ Migration plan saved:", plan.id);
        } catch (dbError) {
          console.error("❌ Database error saving migration plan:", dbError);
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message:
              "Failed to save migration plan. Please check database schema.",
          });
        }

        // Cache the plan
        await CacheService.getOrSet(
          cacheKeys.migrationPlan(plan.id),
          async () => plan,
          { ttl: CACHE_TTL.MIGRATION_PLAN },
        );

        return { plan, analysis };
      } catch (error) {
        console.error("❌ Migration analysis error:", error);
        if (error instanceof TRPCError) {
          throw error;
        }
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message:
            error instanceof Error
              ? error.message
              : "Failed to analyze migration",
        });
      }
    }),

  // Get all migration plans
  getMigrationPlans: protectedProcedure
    .input(z.object({ projectId: z.string() }))
    .query(async ({ ctx, input }) => {
      try {
        const { projectId } = input;
        const userId = ctx.user.userId!;

        const access = await db.userToProject.findUnique({
          where: { userId_projectId: { userId, projectId } },
        });

        if (!access) {
          throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
        }

        const cacheKey = `migration:plans:${projectId}`;

        return await CacheService.getOrSet(
          cacheKey,
          async () => {
            return db.migrationPlan.findMany({
              where: { projectId, userId },
              orderBy: { createdAt: "desc" },
              select: {
                id: true,
                name: true,
                description: true,
                type: true,
                status: true,
                progress: true,
                currentStep: true,
                totalSteps: true,
                githubPrNumber: true,
                githubPrUrl: true,
                githubBranch: true,
                createdAt: true,
                updatedAt: true,
              },
            });
          },
          { ttl: CACHE_TTL.MIGRATION_PLAN },
        );
      } catch (error) {
        console.error("❌ Error fetching migration plans:", error);
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to fetch migration plans",
        });
      }
    }),

  // Get one migration plan
  getMigrationPlan: protectedProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      try {
        const { id } = input;
        const userId = ctx.user.userId!;

        const plan = await db.migrationPlan.findFirst({
          where: { id, userId },
        });

        if (!plan) {
          throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
        }

        return await CacheService.getOrSet(
          cacheKeys.migrationPlan(id),
          async () => plan,
          { ttl: CACHE_TTL.MIGRATION_PLAN },
        );
      } catch (error) {
        console.error("❌ Error fetching migration plan:", error);
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to fetch migration plan",
        });
      }
    }),

  //  Apply migration via GitHub PR
  applyMigrationViaPR: protectedProcedure
    .input(z.object({ planId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const { planId } = input;
      const userId = ctx.user.userId!;

      const plan = await db.migrationPlan.findFirst({
        where: { id: planId, userId },
        include: { project: true },
      });

      if (!plan) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
      }

      const repoUrl = plan.project?.githubUrl;
      if (!repoUrl) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "GitHub URL not found for this project",
        });
      }

      const result = await GitHubMigrationService.applyMigrationViaPR(
        planId,
        userId,
        repoUrl,
      );

      // Update plan with PR info
      if (result.success && result.prNumber && result.prUrl) {
        await db.migrationPlan.update({
          where: { id: planId },
          data: {
            githubPrNumber: result.prNumber,
            githubPrUrl: result.prUrl,
            githubBranch: result.branchName,
            status: "completed",
            progress: 100,
          },
        });
        // Invalidate caches
        await CacheService.invalidate(cacheKeys.migrationPlan(planId));
        await CacheService.invalidate(`migration:plans:${plan.projectId}`);
      }

      return result;
    }),

  //  Rollback via GitHub
  rollbackViaGitHub: protectedProcedure
    .input(z.object({ planId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const { planId } = input;
      const userId = ctx.user.userId!;

      const plan = await db.migrationPlan.findFirst({
        where: { id: planId, userId },
        include: { project: true },
      });

      if (!plan) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
      }

      const repoUrl = plan.project?.githubUrl;
      if (!repoUrl) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "GitHub URL not found for this project",
        });
      }

      const result = await GitHubMigrationService.rollbackViaGitHub(
        planId,
        userId,
        repoUrl,
      );

      // Update plan status
      if (result.success) {
        await db.migrationPlan.update({
          where: { id: planId },
          data: {
            status: "rolled_back",
            githubPrNumber: null,
            githubPrUrl: null,
            githubBranch: null,
          },
        });
        // Invalidate caches
        await CacheService.invalidate(cacheKeys.migrationPlan(planId));
        await CacheService.invalidate(`migration:plans:${plan.projectId}`);
      }

      return result;
    }),

  //  Get migration progress
  getMigrationProgress: protectedProcedure
    .input(z.object({ planId: z.string() }))
    .query(async ({ ctx, input }) => {
      const { planId } = input;
      const userId = ctx.user.userId!;

      const plan = await db.migrationPlan.findFirst({
        where: { id: planId, userId },
      });

      if (!plan) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
      }

      return {
        status: plan.status,
        progress: plan.progress || 0,
        currentStep: plan.currentStep || 0,
        totalSteps: plan.totalSteps || 0,
        prUrl: plan.githubPrUrl,
        prNumber: plan.githubPrNumber,
      };
    }),

  //  Save migration plan (update existing)
  saveMigrationPlan: protectedProcedure
    .input(
      z.object({
        planId: z.string(),
        name: z.string().optional(),
        description: z.string().optional(),
        status: z
          .enum([
            "draft",
            "ready",
            "in_progress",
            "completed",
            "failed",
            "rolled_back",
          ])
          .optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const { planId, ...data } = input;
      const userId = ctx.user.userId!;

      const plan = await db.migrationPlan.findFirst({
        where: { id: planId, userId },
      });

      if (!plan) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
      }

      const updated = await db.migrationPlan.update({
        where: { id: planId },
        data: {
          ...(data.name && { name: data.name }),
          ...(data.description && { description: data.description }),
          ...(data.status && { status: data.status }),
          updatedAt: new Date(),
        },
      });

      // Invalidate caches
      await CacheService.invalidate(cacheKeys.migrationPlan(planId));
      await CacheService.invalidate(`migration:plans:${plan.projectId}`);

      return updated;
    }),

  //  Delete migration plan (already exists)
  deleteMigrationPlan: protectedProcedure
    .input(z.object({ planId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const { planId } = input;
      const userId = ctx.user.userId!;

      const plan = await db.migrationPlan.findFirst({
        where: { id: planId, userId },
      });

      if (!plan) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Plan not found" });
      }

      const projectId = plan.projectId;
      const result = await db.migrationPlan.delete({
        where: { id: planId },
      });

      // Invalidate caches
      await CacheService.invalidate(cacheKeys.migrationPlan(planId));
      await CacheService.invalidate(`migration:plans:${projectId}`);

      return result;
    }),

  detectStack: protectedProcedure
    .input(z.object({ projectId: z.string() }))
    .query(async ({ ctx, input }) => {
      const { projectId } = input;
      const userId = ctx.user.userId!;

      const access = await db.userToProject.findUnique({
        where: { userId_projectId: { userId, projectId } },
      });

      if (!access) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
      }

      const cacheKey = `stack:${projectId}`;

      return await CacheService.getOrSet(
        cacheKey,
        async () => {
          return await detectTechStack(projectId);
        },
        { ttl: CACHE_TTL.MIGRATION_ANALYSIS },
      );
    }),

  getSuggestions: protectedProcedure
    .input(z.object({ projectId: z.string() }))
    .query(async ({ ctx, input }) => {
      const { projectId } = input;
      const userId = ctx.user.userId!;

      const access = await db.userToProject.findUnique({
        where: { userId_projectId: { userId, projectId } },
      });

      if (!access) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
      }

      const cacheKey = `suggestions:${projectId}`;

      return await CacheService.getOrSet(
        cacheKey,
        async () => {
          const stack = await detectTechStack(projectId);
          return await getMigrationSuggestions(projectId, stack);
        },
        {
          ttl: CACHE_TTL.MIGRATION_ANALYSIS,
        },
      );
    }),
});
